import type {
  NavLink,
  Service,
  MaintenancePlan,
  Testimonial,
  TeamMember,
  ServiceArea,
} from "@/types";

export const COMPANY = {
  name: "[Company Name]",
  tagline: "Your Comfort Is Our Family's Mission",
  phone: "(941) 555-0123",
  phoneRaw: "+19415550123",
  email: "info@hvac-englewood.com",
  address: {
    street: "1234 S. Indiana Ave",
    city: "Englewood",
    state: "FL",
    zip: "34223",
    full: "1234 S. Indiana Ave, Englewood, FL 34223",
  },
  hours: {
    weekday: "Mon–Fri: 7:00 AM – 6:00 PM",
    saturday: "Sat: 8:00 AM – 2:00 PM",
    sunday: "Sun: Closed",
    emergency: "24/7 Emergency Service Available",
  },
  social: {
    facebook: "https://facebook.com",
    google: "https://google.com",
    nextdoor: "https://nextdoor.com",
  },
  licenseNumber: "CAC1234567",
  yearsInBusiness: 20,
  reviewCount: 200,
  averageRating: 4.9,
  customersServed: 5000,
};

export const NAV_LINKS: NavLink[] = [
  { label: "Home", href: "/" },
  {
    label: "Services",
    href: "/services",
    children: [
      { label: "Residential AC & Heating", href: "/services/residential" },
      { label: "Commercial HVAC", href: "/services/commercial" },
      { label: "Indoor Air Quality", href: "/services/indoor-air-quality" },
    ],
  },
  { label: "Maintenance Plans", href: "/maintenance-plans" },
  { label: "About Us", href: "/about" },
  { label: "Reviews", href: "/reviews" },
  { label: "Service Areas", href: "/service-areas" },
  { label: "Contact", href: "/contact" },
];

export const SERVICES: Service[] = [
  {
    id: "residential",
    title: "Residential AC & Heating",
    shortTitle: "Residential",
    description:
      "Keep your family comfortable year-round with expert installation, repair, and maintenance for all major brands.",
    icon: "Home",
    href: "/services/residential",
    features: [
      "AC Installation & Replacement",
      "Heating System Repair",
      "Preventive Maintenance",
      "Ductwork Inspection & Repair",
      "Thermostat Installation",
      "Energy Efficiency Upgrades",
    ],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop",
  },
  {
    id: "commercial",
    title: "Commercial HVAC",
    shortTitle: "Commercial",
    description:
      "Reliable climate solutions for businesses, offices, and commercial properties throughout Southwest Florida.",
    icon: "Building2",
    href: "/services/commercial",
    features: [
      "Commercial AC Systems",
      "Rooftop Unit Service",
      "Preventive Maintenance Contracts",
      "Energy Management Systems",
      "New Construction HVAC",
      "Retrofit & Upgrades",
    ],
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop",
  },
  {
    id: "indoor-air-quality",
    title: "Indoor Air Quality",
    shortTitle: "Air Quality",
    description:
      "Breathe easier with professional air quality solutions designed for Florida's humid coastal climate.",
    icon: "Wind",
    href: "/services/indoor-air-quality",
    features: [
      "Duct Cleaning & Sanitizing",
      "Air Purification Systems",
      "Whole-Home Dehumidifiers",
      "UV Germicidal Lights",
      "HEPA Filtration",
      "Humidity Control",
    ],
    image: "https://images.unsplash.com/photo-1631545806609-e5e0b29b567e?w=800&h=600&fit=crop",
  },
  {
    id: "emergency",
    title: "24/7 Emergency Service",
    shortTitle: "Emergency",
    description:
      "AC broke down in the Florida heat? Our emergency technicians are available around the clock. Call now for fast relief.",
    icon: "Siren",
    href: "/contact",
    features: [
      "Available 24/7/365",
      "Fast Response Times",
      "No Overtime Charges",
      "All Major Brands Serviced",
      "Upfront Pricing",
      "Licensed & Insured Technicians",
    ],
    image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&h=600&fit=crop",
  },
];

export const MAINTENANCE_PLANS: MaintenancePlan[] = [
  {
    id: "bronze",
    name: "Bronze",
    monthlyPrice: 12,
    annualPrice: 139,
    features: [
      { text: "1 Annual AC Tune-Up", included: true },
      { text: "Priority Scheduling", included: true },
      { text: "10% Repair Discount", included: true },
      { text: "No Overtime Charges", included: true },
      { text: "Filter Replacements", included: false },
      { text: "Duct Inspection", included: false },
      { text: "Indoor Air Quality Check", included: false },
    ],
    highlighted: false,
    ctaText: "Choose Bronze",
  },
  {
    id: "silver",
    name: "Silver",
    monthlyPrice: 20,
    annualPrice: 229,
    features: [
      { text: "2 Annual Tune-Ups (AC + Heat)", included: true },
      { text: "Priority Scheduling", included: true },
      { text: "15% Repair Discount", included: true },
      { text: "No Overtime Charges", included: true },
      { text: "Filter Replacements (2/year)", included: true },
      { text: "Duct Inspection", included: true },
      { text: "Indoor Air Quality Check", included: false },
    ],
    highlighted: true,
    ctaText: "Choose Silver",
  },
  {
    id: "gold",
    name: "Gold",
    monthlyPrice: 30,
    annualPrice: 349,
    features: [
      { text: "2 Annual Tune-Ups (AC + Heat)", included: true },
      { text: "Priority Scheduling", included: true },
      { text: "20% Repair Discount", included: true },
      { text: "No Overtime Charges", included: true },
      { text: "Filter Replacements (4/year)", included: true },
      { text: "Annual Duct Inspection", included: true },
      { text: "Annual Air Quality Assessment", included: true },
    ],
    highlighted: false,
    ctaText: "Choose Gold",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "Margaret S.",
    text: "After our AC went out in July, they had a technician here within 2 hours. Professional, honest, and fair pricing. We've been customers for 5 years now.",
    rating: 5,
    serviceType: "Emergency Repair",
    date: "2025-11-15",
    source: "Google",
  },
  {
    id: "2",
    name: "Robert & Linda K.",
    text: "Best HVAC company we've dealt with in 30 years of living in Florida. Their maintenance plan has saved us thousands. Highly recommend!",
    rating: 5,
    serviceType: "Maintenance Plan",
    date: "2025-10-22",
    source: "Google",
  },
  {
    id: "3",
    name: "James T.",
    text: "Replaced our entire system. The team was courteous, cleaned up after themselves, and explained everything clearly. No surprises on the bill.",
    rating: 5,
    serviceType: "AC Installation",
    date: "2025-09-30",
    source: "Google",
  },
  {
    id: "4",
    name: "Dorothy M.",
    text: "I'm a senior living alone and I always worry about being taken advantage of. These folks are honest and treat me like family. They even helped me understand my thermostat!",
    rating: 5,
    serviceType: "Residential Service",
    date: "2025-08-18",
    source: "Google",
  },
  {
    id: "5",
    name: "Frank W.",
    text: "Our restaurant's AC died on a Friday evening during season. They came out Saturday morning and had us back up and running. Saved our weekend!",
    rating: 5,
    serviceType: "Commercial Emergency",
    date: "2025-07-05",
    source: "Google",
  },
  {
    id: "6",
    name: "Patricia H.",
    text: "The humidity in our home was causing mold issues. They installed a whole-home dehumidifier and the difference is night and day. Should've done it years ago!",
    rating: 5,
    serviceType: "Indoor Air Quality",
    date: "2025-06-12",
    source: "Google",
  },
  {
    id: "7",
    name: "William & Jean A.",
    text: "Moved here from Ohio and needed a reliable HVAC company. A neighbor recommended them and we couldn't be happier. Fair, friendly, and always on time.",
    rating: 4,
    serviceType: "Residential Service",
    date: "2025-05-20",
    source: "Nextdoor",
  },
  {
    id: "8",
    name: "Carol D.",
    text: "Their Gold maintenance plan gives us such peace of mind. Every visit, the technician is thorough and takes time to answer my questions. Worth every penny.",
    rating: 5,
    serviceType: "Maintenance Plan",
    date: "2025-04-08",
    source: "Google",
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: "1",
    name: "John Doe",
    role: "Owner & Lead Technician",
    bio: "With over 20 years of experience in Southwest Florida HVAC, John founded the company with a simple mission: treat every customer like family.",
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop",
  },
  {
    id: "2",
    name: "Jane Doe",
    role: "Operations Manager",
    bio: "Jane keeps everything running smoothly, from scheduling to customer care. She's the friendly voice you'll hear when you call.",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop",
  },
  {
    id: "3",
    name: "Mike Johnson",
    role: "Senior Technician",
    bio: "NATE-certified with 15 years of experience, Mike specializes in complex installations and system diagnostics.",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop",
  },
  {
    id: "4",
    name: "Sarah Williams",
    role: "Service Technician",
    bio: "Sarah brings 8 years of residential and commercial experience. Customers love her attention to detail and clear explanations.",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop",
  },
];

export const SERVICE_AREAS: ServiceArea[] = [
  { name: "Englewood", description: "Our hometown — fast response times guaranteed" },
  { name: "North Port", description: "Full residential and commercial service" },
  { name: "Venice", description: "Serving the Venice island and mainland" },
  { name: "Port Charlotte", description: "Comprehensive HVAC services" },
  { name: "Punta Gorda", description: "Including Burnt Store and Punta Gorda Isles" },
  { name: "Rotonda West", description: "Serving all of Rotonda's communities" },
  { name: "Boca Grande", description: "Island service available" },
  { name: "Placida", description: "Full service coverage" },
  { name: "Grove City", description: "Right in our backyard" },
  { name: "Manasota Key", description: "Barrier island service" },
  { name: "Osprey", description: "Extending north into Sarasota County" },
  { name: "Nokomis", description: "Full service for Nokomis residents" },
];
